name: demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_background_service: ^0.2.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.3
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
